/*
Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	time "time"

	coreoamdevv1alpha1 "github.com/oam-dev/admission-controller/pkg/apis/core.oam.dev/v1alpha1"
	versioned "github.com/oam-dev/admission-controller/pkg/client/clientset/versioned"
	internalinterfaces "github.com/oam-dev/admission-controller/pkg/client/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/oam-dev/admission-controller/pkg/client/listers/core.oam.dev/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// ScopeInformer provides access to a shared informer and lister for
// Scopes.
type ScopeInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.ScopeLister
}

type scopeInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewScopeInformer constructs a new informer for Scope type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewScopeInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredScopeInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredScopeInformer constructs a new informer for Scope type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredScopeInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.CoreV1alpha1().Scopes(namespace).List(options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.CoreV1alpha1().Scopes(namespace).Watch(options)
			},
		},
		&coreoamdevv1alpha1.Scope{},
		resyncPeriod,
		indexers,
	)
}

func (f *scopeInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredScopeInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *scopeInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&coreoamdevv1alpha1.Scope{}, f.defaultInformer)
}

func (f *scopeInformer) Lister() v1alpha1.ScopeLister {
	return v1alpha1.NewScopeLister(f.Informer().GetIndexer())
}
