/*
Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"time"

	v1alpha1 "github.com/oam-dev/admission-controller/pkg/apis/core.oam.dev/v1alpha1"
	scheme "github.com/oam-dev/admission-controller/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// ScopesGetter has a method to return a ScopeInterface.
// A group's client should implement this interface.
type ScopesGetter interface {
	Scopes(namespace string) ScopeInterface
}

// ScopeInterface has methods to work with Scope resources.
type ScopeInterface interface {
	Create(*v1alpha1.Scope) (*v1alpha1.Scope, error)
	Update(*v1alpha1.Scope) (*v1alpha1.Scope, error)
	UpdateStatus(*v1alpha1.Scope) (*v1alpha1.Scope, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.Scope, error)
	List(opts v1.ListOptions) (*v1alpha1.ScopeList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.Scope, err error)
	ScopeExpansion
}

// scopes implements ScopeInterface
type scopes struct {
	client rest.Interface
	ns     string
}

// newScopes returns a Scopes
func newScopes(c *CoreV1alpha1Client, namespace string) *scopes {
	return &scopes{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the scope, and returns the corresponding scope object, and an error if there is any.
func (c *scopes) Get(name string, options v1.GetOptions) (result *v1alpha1.Scope, err error) {
	result = &v1alpha1.Scope{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("scopes").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of Scopes that match those selectors.
func (c *scopes) List(opts v1.ListOptions) (result *v1alpha1.ScopeList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.ScopeList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("scopes").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested scopes.
func (c *scopes) Watch(opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("scopes").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a scope and creates it.  Returns the server's representation of the scope, and an error, if there is any.
func (c *scopes) Create(scope *v1alpha1.Scope) (result *v1alpha1.Scope, err error) {
	result = &v1alpha1.Scope{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("scopes").
		Body(scope).
		Do().
		Into(result)
	return
}

// Update takes the representation of a scope and updates it. Returns the server's representation of the scope, and an error, if there is any.
func (c *scopes) Update(scope *v1alpha1.Scope) (result *v1alpha1.Scope, err error) {
	result = &v1alpha1.Scope{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("scopes").
		Name(scope.Name).
		Body(scope).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *scopes) UpdateStatus(scope *v1alpha1.Scope) (result *v1alpha1.Scope, err error) {
	result = &v1alpha1.Scope{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("scopes").
		Name(scope.Name).
		SubResource("status").
		Body(scope).
		Do().
		Into(result)
	return
}

// Delete takes name of the scope and deletes it. Returns an error if one occurs.
func (c *scopes) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("scopes").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *scopes) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("scopes").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched scope.
func (c *scopes) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.Scope, err error) {
	result = &v1alpha1.Scope{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("scopes").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
